M48
; DRILL file {KiCad (6.0.0)} date Wed Mar 16 00:11:58 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-16T00:11:58-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X134.62Y-62.484
X141.986Y-62.484
T2
X137.0Y-27.0
X137.0Y-97.0
X177.0Y-27.0
X177.0Y-97.0
T0
M30
